version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mn-efs-nodejs-vpc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-86rvgpysomdn"
s3_prefix = "mn-efs-nodejs-vpc"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"

